# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Seungwon Kim
og_image: /assets/img/profile_sw2.png

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  resume:
    - type: resume
      name: Resume
      link: /assets/docs/cv_seungwonkim.pdf
  follow:
    - type: linkedin
      name: LinkedIn
      link: https://www.linkedin.com/in/seungwon-kim/
    - type: github
      name: GitHub
      link: https://github.com/seungwon1
  contact:
    - type: email
      name: Email
      value: pennymagic156@gmail.com

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
